### ISSUE TITLE
AIFF-C Support

### ISSUE THREAD

**Issue by davehofmann** [davehofmann/wave-recovery-tool#3]
Support analyzing and restoring AIFF-C files as requested by @joekroese in #2.

**Comment by davehofmann** [comment]
@joekroese I implemented AIFF-C support and I was able to restore the file you sent me in #2.
The command line is:
```
python3 waverecovery.py -r -b 32 -c 2 damaged.aiff restored.aiff
```
Could you please confirm that this works for you?

**Comment by joekroese** [comment]
Amazing @davehofmann! The same command fixes it for me too. Never thought I'd hear the audio from that set again. Thanks so much! 🙏

**Comment by davehofmann** [comment]
Great, I'm glad your recording could be restored 👍  Closing this issue.
